default_context:
    full_name: "Thorsten Beier"
    email: "derthorstenbeier@gmail.com"
    github_username: "DerThorsten"
    azure_username: "derthorstenbeier"
    python_package_name: "my-py-tools"