version: 2
variables:



  install_conda_build_and_cookiecutter: &install_conda_build_and_cookiecutter
    run:
      name: Config and Update Conda
      command: |
        conda install cookiecutter -c conda-forge 
        conda install conda-build
  run_test_conda_build: &run_test_conda_build
    run:
      name: Run tests
      command: |
        conda build recipe -c conda-forge

  update_conda: &update_conda
    run:
      name: update conda
      command: |
        conda config --set always_yes yes --set changeps1 no
        conda update -q conda 
        conda init bash

  run_test_script: &run_test_script
    run:
      name: Run test scripts
      command: |
        conda init bash
        chmod +x .ci/test_project.sh 
        ./.ci/test_project.sh 

jobs:
  test_job:
    docker:
     - image: continuumio/miniconda3:4.5.12
    working_directory: ~/repo
    steps:
      - checkout
      - *update_conda
      - *run_test_script

  test_conda_build_job:
    docker:
     - image: continuumio/miniconda3:4.5.12
    working_directory: ~/repo
    steps:
      - checkout
      - *update_conda
      - *install_conda_build_and_cookiecutter
      - *run_test_conda_build

workflows:
  version: 2

  my_test:
    jobs:
      - test_job
      - test_conda_build_job

  nightly-test:
    triggers:
       - schedule:
            cron: "0 0 * * *"
            filters:
              branches:
                only:
                  - master
    jobs:
       - test_job
       - test_conda_build_job

